"""
Detection Signal 1: LLM Classifier (Groq Llama 3.3)

Measures overall writing style, coherence, tone, and semantic patterns, and
produces an AI-likelihood score between 0.0 (appears human-written) and 1.0
(appears AI-generated).

Uses the Groq API (Llama 3.3) and asks the model to return a structured JSON
object, then parses and validates a single AI-likelihood score.
"""

import json
import os

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

# Groq Llama 3.3 model specified in the planning document.
MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are a text-provenance analyst. You judge whether a piece of text was "
    "written by a human or generated by an AI language model, based on writing "
    "style, coherence, tone, and semantic patterns.\n\n"
    "Respond with ONLY a JSON object in exactly this form:\n"
    '{"ai_likelihood": <number between 0.0 and 1.0>}\n\n'
    "0.0 means the text appears entirely human-written; 1.0 means it appears "
    "entirely AI-generated. Do not include any explanation or extra text."
)


def get_llm_ai_score(text: str) -> float:
    """Return an AI-likelihood score in [0.0, 1.0] for the given text.

    0.0 means the text appears human-written; 1.0 means it appears
    AI-generated. On any API or parsing failure, returns 0.5 (fully uncertain)
    so the caller always receives a valid score.

    Args:
        text: The submitted text to analyze.

    Returns:
        A float in the range [0.0, 1.0].
    """
    try:
        client = Groq(api_key=os.environ["GROQ_API_KEY"])
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        content = response.choices[0].message.content
        data = json.loads(content)
        score = float(data["ai_likelihood"])
        # Clamp to the valid range in case the model drifts outside [0, 1].
        return max(0.0, min(1.0, score))
    except (KeyError, ValueError, TypeError, json.JSONDecodeError):
        # Malformed or missing score in the response.
        return 0.5
    except Exception:
        # Network issues, auth errors, rate limits, etc.
        return 0.5
